# Generated by Django 2.0.6 on 2018-07-25 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('cover', models.ImageField(null=True, upload_to='book_cover')),
                ('market_price', models.FloatField()),
                ('dang_price', models.FloatField()),
                ('sales_amount', models.BigIntegerField()),
                ('publisher', models.CharField(max_length=20)),
                ('publish_time', models.DateField()),
                ('page_number', models.IntegerField()),
                ('edition', models.IntegerField()),
                ('words_number', models.BigIntegerField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('editer_recommend', models.TextField()),
                ('brief_introduction', models.TextField()),
                ('author_introduction', models.TextField()),
                ('catalogue', models.TextField()),
                ('media_comments', models.TextField()),
                ('tips_chapter', models.TextField()),
            ],
            options={
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('cate_number', models.FloatField()),
                ('parent_id', models.FloatField(null=True)),
                ('amount', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 't_category',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='cate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Category'),
        ),
    ]
