# Generated by Django 2.0.6 on 2018-07-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cate_number',
        ),
    ]
