# Generated by Django 2.0.6 on 2018-07-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180729_0825'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='t_address',
        ),
        migrations.AlterModelTable(
            name='order',
            table='t_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='t_orderitem',
        ),
    ]
